# Generated by Django 5.1.6 on 2025-09-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("TASK_DUE_SOON", "Task Due Soon"),
                    ("TASK_OVERDUE", "Task Overdue"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("PROJECT_INVITATION", "Project Invitation"),
                    ("PROJECT_UPDATE", "Project Update"),
                    ("MESSAGE", "Message"),
                    ("DISCUSSION_REPLY", "Discussion Reply"),
                    ("MENTION", "Mention"),
                    ("SYSTEM", "System Notification"),
                    ("ANNOUNCEMENT", "Announcement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("TASK_DUE_SOON", "Task Due Soon"),
                    ("TASK_OVERDUE", "Task Overdue"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("PROJECT_INVITATION", "Project Invitation"),
                    ("PROJECT_UPDATE", "Project Update"),
                    ("MESSAGE", "Message"),
                    ("DISCUSSION_REPLY", "Discussion Reply"),
                    ("MENTION", "Mention"),
                    ("SYSTEM", "System Notification"),
                    ("ANNOUNCEMENT", "Announcement"),
                ],
                max_length=20,
            ),
        ),
    ]
