# Generated by Django 5.2.6 on 2025-09-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_email_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sms_notifications",
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
